version: '3.8'
services:
  db:
    container_name: postgredb
    image: postgres
    restart: always
    volumes: 
      - ./db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - docker.env

networks:
  default:
    name: postgre-service_default